### ISSUE TITLE
Feature Request: Different Starting of Animation

### ISSUE THREAD

**Issue by doctopus** [nickzman/hyperspace#1]
This is an amazing view of hyperspace in 60fps. However it being a screensaver it is seen for the initial few seconds. Since it starts exactly at the same sequence, most of the amazing visuals are often never experienced. If it could be made to start at different starting point it would appeal to the visual satisfaction. Thank you.

**Comment by nickzman** [comment]
Thanks, but I have no plans to introduce any new features to Hyperspace. If you'd like to work on such a feature, the source code is open to you.
